# Generated by Django 4.0.4 on 2022-05-20 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neworder',
            old_name='is_ordered',
            new_name='is_order',
        ),
    ]
