# Generated by Django 4.0.4 on 2022-05-20 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_is_ordered_neworder_is_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neworder',
            old_name='is_order',
            new_name='is_ordered',
        ),
    ]
